BUILTIN_ANIMATIONS = {
    0: "Rainbow Gradual Chase",
    1: "Rainbow Comet",
    2: "Rainbow Segment",
    3: "Rainbow Wave",
    4: "Rainbow Meteor",
    5: "Rainbow Gradual",
    6: "Rainbow Jump",
    7: "Rainbow Stars",
    8: "Rainbow Fade In Out",
    9: "Rainbow Spin",
    10: "Red Stacking",
    11: "Green Stacking",
    12: "Blue Stacking",
    13: "Yellow Stacking",
    14: "Cyan Stacking",
    15: "Purple Stacking",
    16: "White Stacking",
    17: "Full Color Stack",
    18: "Red to Green Stack",
    19: "Green to Blue Stack",
    20: "Blue to Yellow Stack",
    21: "Yellow to Cyan Stack",
    22: "Cyan to Purple Stack",
    23: "Purple to White Stack",
    24: "Red Comet",
    25: "Green Comet",
    26: "Blue Comet",
    27: "Yellow Comet",
    28: "Cyan Comet",
    29: "Purple Comet",
    30: "White Comet",
    31: "Red Meteor",
    32: "Green Meteor",
    33: "Blue Meteor",
    34: "Yellow Meteor",
    35: "Cyan Meteor",
    36: "Purple Meteor",
    37: "White Meteor",
    38: "Red Wave",
    39: "Green Wave",
    40: "Blue Wave",
    41: "Yellow Wave",
    42: "Cyan Wave",
    43: "Purple Wave",
    44: "White Wave",
    45: "Red Green Wave",
    46: "Red Blue Wave",
    47: "Red Yellow Wave",
    48: "Red Cyan Wave",
    49: "Red Purple Wave",
    50: "Red White Wave",
    51: "Green Blue Wave",
    52: "Green Yellow Wave",
    53: "Green Cyan Wave",
    54: "Green Purple Wave",
    55: "Green White Wave",
    56: "Blue Yellow Wave",
    57: "Blue Cyan Wave",
    58: "Blue Purple Wave",
    59: "Blue White Wave",
    60: "Yellow Cyan Wave",
    61: "Yellow Purple Wave",
    62: "Yellow White Wave",
    63: "Cyan Purple Wave",
    64: "Cyan White Wave",
    65: "Purple White Wave",
    66: "Red Dot Pulse",
    67: "Green Dot Pulse",
    68: "Blue Dot Pulse",
    69: "Yellow Dot Pulse",
    70: "Cyan Dot Pulse",
    71: "Purple Dot Pulse",
    72: "White Dot Pulse",
    73: "Red Green Blank Pulse",
    74: "Green Blue Blank Pulse",
    75: "Blue Yellow Blank Pulse",
    76: "Yellow Cyan Blank Pulse",
    77: "Cyan Purple Blank Pulse",
    78: "Purple White Blank Pulse",
    79: "Red with Purple Pulse",
    80: "Green with Cyan Pulse",
    81: "Blue with Yellow Pulse",
    82: "Yellow with Blue Pulse",
    83: "Cyan with Green Pulse",
    84: "Purple with Purple Pulse",
    85: "Red Comet Spin",
    86: "Green Comet Spin",
    87: "Blue Comet Spin",
    88: "Yellow Comet Spin",
    89: "Cyan Comet Spin",
    90: "Purple Comet Spin",
    91: "White Comet Spin",
    92: "Red Dot Spin",
    93: "Green Dot Spin",
    94: "Blue Dot Spin",
    95: "Yellow Dot Spin",
    96: "Cyan Dot Spin",
    97: "Purple Dot Spin",
    98: "White Dot Spin",
    99: "Red Segment Spin",
    100: "Green Segment Spin",
    101: "Blue Segment Spin",
    102: "Yellow Segment Spin",
    103: "Cyan Segment Spin",
    104: "Purple Segment Spin",
    105: "White Segment Spin",
    106: "Red Green Gradual Snake",
    107: "Red Blue Gradual Snake",
    108: "Red Yellow Gradual Snake",
    109: "Red Cyan Gradual Snake",
    110: "Red Purple Gradual Snake",
    111: "Red White Gradual Snake",
    112: "Green Blue Gradual Snake",
    113: "Green Yellow Gradual Snake",
    114: "Green Cyan Gradual Snake",
    115: "Green Purple Gradual Snake",
    116: "Green White Gradual Snake",
    117: "Blue Yellow Gradual Snake",
    118: "Blue Cyan Gradual Snake",
    119: "Blue Purple Gradual Snake",
    120: "Blue White Gradual Snake",
    121: "Yellow Cyan Gradual Snake",
    122: "Yellow Purple Gradual Snake",
    123: "Yellow White Gradual Snake",
    124: "Cyan Purple Gradual Snake",
    125: "Cyan White Gradual Snake",
    126: "Purple White Gradual Snake",
    127: "Red White Blank Snake",
    128: "Green White Blank Snake",
    129: "Blue White Blank Snake",
    130: "Yellow White Blank Snake",
    131: "Cyan White Blank Snake",
    132: "Purple White Blank Snake",
    133: "Green Yellow White Snake",
    134: "Red Green White Snake",
    135: "Red Yellow Snake",
    136: "Red White Snake",
    137: "Green White Snake",
    138: "Red Stars",
    139: "Green Stars",
    140: "Blue Stars",
    141: "Yellow Stars",
    142: "Cyan Stars",
    143: "Purple Stars",
    144: "White Stars",
    145: "Red Background Stars",
    146: "Green Background Stars",
    147: "Blue Background Stars",
    148: "Yellow Background Stars",
    149: "Cyan Background Stars",
    150: "Purple Background Stars",
    151: "Red White Background Stars",
    152: "Green White Background Stars",
    153: "Blue White Background Stars",
    154: "Yellow White Background Stars",
    155: "Cyan White Background Stars",
    156: "Purple White Background Stars",
    157: "White White Background Stars",
    158: "Red Breath",
    159: "Green Breath",
    160: "Blue Breath",
    161: "Yellow Breath",
    162: "Cyan Breath",
    163: "Purple Breath",
    164: "White Breath",
    165: "Red Yellow Fire",
    166: "Red Purple Fire",
    167: "Green Yellow Fire",
    168: "Green Cyan Fire",
    169: "Blue Purple Fire",
    170: "Blue Cyan Fire",
    171: "Red Strobe",
    172: "Green Strobe",
    173: "Blue Strobe",
    174: "Yellow Strobe",
    175: "Cyan Strobe",
    176: "Purple Strobe",
    177: "White Strobe",
    178: "Red Blue White Strobe",
    179: "Full Color Strobe",
}
